### PR TITLE
新增简单日志打印

### PR DESCRIPTION
**Pull request by WilliamWongQAQ**
新增简单日志打印

### CODE REVIEW

**Comment by ZhengZhenyu** [comment]
Please add capability to specify log dir, and log level and config a default dir and default log level in conf.yaml

**Comment by WilliamWongQAQ** [comment]
Now i've added log_level and  log_dir configs in conf.yaml, it can take effect.  
  And i optimize the log module, i test the scrpit twice, it can run successfully.

**Comment by WilliamWongQAQ** [comment]
upload omniimager-v.0.2.3.tar.gz successfully

**Comment by ZhengZhenyu** [comment]
LGTM

**Pull request merged**
